// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCcqwnKuszOYxW_yViRdyp-6WGKIwSUE0',
    appId: '1:210717632685:web:5224a3693bbbf87455be24',
    messagingSenderId: '210717632685',
    projectId: 'dearliveryapp',
    authDomain: 'dearliveryapp.firebaseapp.com',
    storageBucket: 'dearliveryapp.firebasestorage.app',
    measurementId: 'G-CCLC7DGJYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7X0xme2R1prlqPXOrffV5fnbi_fjmX0c',
    appId: '1:210717632685:android:c86c179a7a22f5f655be24',
    messagingSenderId: '210717632685',
    projectId: 'dearliveryapp',
    storageBucket: 'dearliveryapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALfclL2iodlwKwq9kBv9rHsU119vJD12g',
    appId: '1:210717632685:ios:0b5f8fb9c6fda3af55be24',
    messagingSenderId: '210717632685',
    projectId: 'dearliveryapp',
    storageBucket: 'dearliveryapp.firebasestorage.app',
    iosBundleId: 'com.example.dearLivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALfclL2iodlwKwq9kBv9rHsU119vJD12g',
    appId: '1:210717632685:ios:0b5f8fb9c6fda3af55be24',
    messagingSenderId: '210717632685',
    projectId: 'dearliveryapp',
    storageBucket: 'dearliveryapp.firebasestorage.app',
    iosBundleId: 'com.example.dearLivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCcqwnKuszOYxW_yViRdyp-6WGKIwSUE0',
    appId: '1:210717632685:web:68a4cbc1aa8c2e2b55be24',
    messagingSenderId: '210717632685',
    projectId: 'dearliveryapp',
    authDomain: 'dearliveryapp.firebaseapp.com',
    storageBucket: 'dearliveryapp.firebasestorage.app',
    measurementId: 'G-2M9JTWETPL',
  );
}
